/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jlafnpqeyrzxywrjnihj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsYWZucHFleXJ6eHl3cmpuaWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0MzIwNDMsImV4cCI6MjA5NDAwODA0M30.dD8Xuii7ZmAPXIOAzP-e5-4ZiSXclUPjTKqu_6RqG-U"